### ISSUE TITLE
Twilio alternatives

### ISSUE THREAD

**Issue by danielrobertson** [nhwhite3118/ThunderBuddy#12]
With Twilio's base price of $1/mo + $0.0075/sms, here's some example costs: 
- 10 ThunderBuddy subscribers -> $1/mo + $0.0075/sms \* 10 users = $3.25/month, which is reasonable.  
- 100 ThunderBuddy subscribers -> $1/mo + $0.0075/sms \* 100 users = $23.50/month :-1: 

In the interest of shelling out no more than just a few bucks per month, I'd say we should either just not accept a large number of users (like after 10 subscribers say, "oh sorry, ThunderBuddy is in beta so we're not accepting more users" which is a lousy thing to do) _or_ we investigate feasible alternates to reaching subscribers using some or all of the ideas here: 
- [SMS Gateways](https://en.wikipedia.org/wiki/SMS_gateway). Emailing number@carrier.com for most carriers sends a text to their number. Then, we could use the [Google Mail API](https://developers.google.com/gmail/api/guides/sending#creating_messages) to send the email. To look up a phone number's carrier without asking the user we could use [Twilio's Lookup API](https://www.twilio.com/lookup) which costs $0.005/lookup and that's fine b/c we'll only lookup once per user then store in database, so 100 users subscribe -> $0.50 :+1: 
- [Google Voice SMS](https://support.google.com/voice/answer/115116?rd=1). Only did brief research and it seems to be free, but has a limit to the number of texts... needs more research

**Comment by nhwhite3118** [comment]
Those numbers are a bit off for the twilio pricing, but I think SMS Gateways are the way to go for cheap scalability.
My napkin math, assuming one thunderstorm/mo: 
- 10 subscribers \* 3 texts/mo \* $0.01/sms (rounded up) + $1/number/mo = $1.30/mo
- 100 subscribers \* 3 texts/mo \* $0.01/sms (rounded up) + $1/number/mo = $4/mo
- 1000 subscribers \* 3 texts/mo \* $0.01/sms (rounded up) + $1/number/mo = $31/mo

**Comment by danielrobertson** [comment]
Sweet, ok well let's plan on using Twilio to find the carrier, then GMail to send an email with the message. 
I'll create issues for those tasks.
