### ISSUE TITLE
Run ThunderBuddy on schedule e.g. every 24 hours 

### ISSUE THREAD

**Issue by danielrobertson** [nhwhite3118/ThunderBuddy#19]
linux cron jobs are a good solution

**Comment by nhwhite3118** [comment]
I need access to the server to do anything with cron. You should be able to do it in a few seconds though.
1. Run `crontab -e` on the command line, pick your favorite editor from the list, then add the following line to the file it opens
   `0     11     *     *     *         pyton3 <FILEPATH TO thunderbuddy.py FROM YOUR HOME DIRECTORY>`

This will run it on the 0th minute of the 11th hour of every day of every month of every year.

**Comment by danielrobertson** [comment]
Perfect. Ok looks like our ubuntu server is in a timezone 1 hour ahead of ours, so I just did a trial run by setting it to 8pm and it works! I got the debug "Thunder" message as well as an ACTUAL message about thunder on Sunday night. I'll remove the debug statement and set the cron job to 11am CST...
